### ISSUE TITLE
在客户端生成验证码？

### ISSUE THREAD

**Issue by linroid** [Freshman111/VerificationCodeView#1]
意义何在？

**Comment by Freshman111** [comment]
有时候这只是一个防止用户不断操作的手段，客户端生成也行

也可以暴露一个方法设置验证码，从服务器请求验证码，就不需要自己生成了，直接绘制验证码就行了

**Comment by bruce3x** [comment]
客户端生成的话，直接扒 API 就绕过了 …… 并没有什么意义吧
